### PR TITLE
Setting a default from address for emails

### PR DESCRIPTION
**Pull request by spilth**
## Problem

While testing out the sendmail switch, sending email now generated the following error:

```
ArgumentError (SMTP From address may not be blank: nil)
```

## Solution

Set a default from email address for ActionMailer: `no-reply@geo.nyu.edu`

## Type

bug-fix

### CODE REVIEW

**Comment by mnyrop** [comment]
@spilth I just sent an email to `no-reply@geo.nyu.edu` to see who that alias routes to / who controls it. I'm worried it might go to someone no longer at NYU, so we'll want to confirm it's a good one to use before merging. (cc @nmwolf @ekate)

**Comment by spilth** [comment]
@mnyrop Thank you for checking. I took it for granted that a `no-reply` email address goes nowhere.

**Comment by mnyrop** [comment]
You're right that it shouldn't (it would be unfortunate if someone is getting spammed!) but I also wish we knew who controlled it so we know who can change SMTP settings if needed.

I'm assuming since it's @ geo.nyu.edu and not @ nyu.edu that there is a mail server running on the EC2...? Unless it's somehow aliased to an NYU via google apps account...? I'm lobbing shots in the dark but am now leaning towards approving & merging the PR now, having you test that it works for what we need, and worrying about that detail later. What would your preference be?

**Comment by spilth** [comment]
@mnyrop I say we try out the email address you sent me in Slack and we see if it works in staging. If it does, then we'll just need to find the right address. If it doesn't, then we'll need to figure something else out 😅

**Review by mnyrop — APPROVED** [review]

**Pull request merged**
